
name: Android CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt keystore
        run: ./decrypt_keystore.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
          PROPERTIES_PASSPHRASE: ${{ secrets.PROPERTIES_PASSPHRASE }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Assemble and upload with Gradle
        run: ./gradlew app:assembleRelease app:appDistributionUploadRelease