
name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Print github ref
        run: echo $GITHUB_REF
        env:
          GITHUB_REF: ${{ github.ref }}
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt keystore
        run: ./decrypt_keystore.sh
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
          PROPERTIES_PASSPHRASE: ${{ secrets.PROPERTIES_PASSPHRASE }}
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Assemble and upload with Gradle
        run: ./gradlew app:assembleRelease app:appDistributionUploadRelease
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}